#!/bin/sh

echo "Switching to branch master"
git checkout master

echo "Building app"
npm run build

echo "Deploying files to server"
rsync -avP build/ tasmara@getinsignia.com:/var/www/getinsignia.com/
echo "Deployment complete"